### ISSUE TITLE
Using the client directly?

### ISSUE THREAD

**Issue by dtrinh100** [gbicou/nuxt-urql#38]
How can I access the client directly? I want to do something like this:

```
client
  .query('{ test }', {
    /* vars */
  })
  .toPromise()
  .then(result => {
    console.log(result); // OperationResult
  });
```

In regular Urql, I would create a client, then export the client to be used outside of Vue components. How can I do this using Nuxt Urql? From my understanding is that Nuxt Urql already creates the client in the Nuxt config file, but is there a way to access that client somehow without defining a new one?

**Comment by gbicou** [comment]
Hi,

You can call `useClientHandle` to retrieve the client:

```ts
const handle = useClientHandle();

handle.client
  .query("{ test }", {
    /* vars */
  })
  .toPromise()
  .then((result) => {
    console.log(result); // OperationResult
  });
```

See https://formidable.com/open-source/urql/docs/basics/vue/#chaining-calls-in-vue-suspense


Or an alternative to retrieve the client injected in the nuxt app:

```ts
const { $urql } = useNuxtApp();

$urql.query("{ test }", {
    /* vars */
  })
  .toPromise()
  .then((result) => {
    console.log(result); // OperationResult
  });
```

**Comment by dtrinh100** [comment]
I tried

```
const { $urql } = useNuxtApp();

$urql.query("{ test }", {
    /* vars */
  })
  .toPromise()
  .then((result) => {
    console.log(result); // OperationResult
  });
```

But I am getting the error: '$urql' is of type 'unknown', How would I resolve this?

**Comment by productdevbook** [comment]
The same problem applies to me. example `defineNuxtRouteMiddleware` dont used. pleaa re open issua

**Comment by gbicou** [comment]
Looks like `{ $urql }` is more an autocomplete failure with code editor.

Nevertheless, version 1.7.0 introduces the `useUrqlClient` composable to access the URQL Client directly : 03b102dfd1eb66f0180344d908a12f11f3f6f91b

See [documentation](https://nuxt-urql-docs.vercel.app/guide/usage#useurqlclient) for usage
