### ISSUE TITLE
Feature Request: Allow access to client outside of Nuxt components

### ISSUE THREAD

**Issue by dtrinh100** [gbicou/nuxt-urql#40]
I have a use case where I want to abstract out some of my GraphQL logic and put them into separate Typescript files. In these files, I don't have access to `setup` or any of the Vue's lifecycle hook. If possible, I want a way to access the client that was created in the `nuxt.config.ts` file and use it outside of the Nuxt components.

**Comment by gbicou** [comment]
I think it's a chicken-egg problem, the client in nuxt-urql is created in a nuxt plugin, so the client is accessible in a nuxt environment...

**Comment by gbicou** [comment]
I would recommend using graphql code generator https://the-guild.dev/graphql/codegen to keep your operations in graphql files and let codegen build the typescript files.
